[project]
name = "mero"
version = "0.1.0"
description = "Mean vs. robust aggregators on distributed heterogeneous data"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "byzfl>=0.0.11",
    "loguru>=0.7.3",
    "typer>=0.19.2",
]

[tool.uv.sources]
byzfl = { workspace = true }